//Universal usage
import 'package:google_fonts/google_fonts.dart';

const txtTypeMessage = "Select user type";
const txtUser = "User";
const txtBusiness = "Business";
const txtSinger = "Singer";
const txtRestaurant = "Restaurant";
const txtCameraMan = "Cameraman";
const txtPhotographer = "Photographer";
const txtCameraManAndPhotographer = "CameraMan and Photographer";
const txtDJ = "DJ";
const txtDancers = "Dancers";
const txtDecor = "Decor";
const txtHairdressersAndMakeupArtists = "Hairdressers and Makeup Artists";
const txtEmail = "Email ID";
const txtName = "Name";
const txtHome = "Home";
const txtAddManageRestaurant= "ADD / MANAGE RESTAURANTS";
const txtManageRestaurantMenu= "MANAGE RESTAURANT MENUS";
const txtSurname = "Surname";
const txtPhnNumber = "Phone Number";
const txtPassword = "Password";
const txtTitle = "Title";
const txtDesc = "Description";
const txtAllRest = "ALL RESTAURANTS";
const txtCatListTitle = "EKLIPS RESORT";
const txtCatDesc = "Category description";
const txtCatName = "Category name";
const txtCatListSubTitle1 = "Price: per person: €30.00";
const txtCatListSubTitle2 = "Min. people: 150";
const txtCatListSubTitle3 = "Max. people: 450";
const txtCatListSubTitle4 = "Rr. Elbasan, km 5, opposite TEG, Albania";
const txtHouseNumber = "Number of house, building, apartment";
const txtStreet = "Street";
const txtNeighbourhood = "Neighborhood";
const txtPostCode = "Post code";
const txtConfirmPassword = "Confirm password";
const txtForGotPassword = "Forgot Password ?";
const txtSignIn = "Sign In";
const txtDontHaveAccount = "Don't have an account ?";
const txtHaveAccount = "Have an account ?";
const txtSignUp = "Sign up";
const txtUploadId = "Upload an ID";
const txtBusinessName = "Business name";
const txtBusinessType = "Type of business";
const txtSubmit = "Submit";
const txtForgotMsg = "Don't worry we just need your \n register email address and its done";
const txtMedia = "Media";
const txtBlog = "Blog";
const txtContactUs = "Contact us";
const txtAboutUs = "About us";
const txtPrivacyPolicy = "Privacy Policy";
const txtMinPeople = "Min.People";
const txtMaxPeople = "Max.People";
const txtPartyName = "Name of party";
const txtService = "Service";
const txtPricePerPerson = "Price per person";
const txtDescription = "Description";
const txtDetail = "Detail";
const txtCalendar = "Calendar";
const txtMenu = "Menu";
const txtEquipment = "Equipment";
const txtFreeServices = "Free Services";
const txtPhotos = "Photos";
const txtLocation = "Location";
const txtComment = "Comment";
const txtSkills = "Skills";
const txtResOtherInfo = "Restaurant Other info.";
const txtResBasicInfo = "Restaurant Basic info.";
const txtSingerOtherInfo = "Singer Other info.";
const txtSingerBasicInfo = "Singer Basic info.";
const txtCameraOtherInfo = "Cameraman Other info.";
const txtCameraBasicInfo = "Cameraman Basic info.";
const txtPhotographerOtherInfo = "Photographer Other info.";
const txtPhotographerBasicInfo = "Photographer Basic info.";
const txtDecorationOtherInfo = "Decoration Other info.";
const txtDecorationBasicInfo = "Decoration Basic info.";
const txtHairdressersMakeupOtherInfo = "Hairdressers and makeup Other info.";
const txtHairdressersMakeupBasicInfo = "Hairdressers and makeup Basic info.";
const txtDjOtherInfo = "DJ Other info.";
const txtDjBasicInfo = "DJ Basic info.";
const txtDancersOtherInfo = "Dancers Other info.";
const txtDancersBasicInfo = "Dancers Basic info.";
const txtPhotosOfTheRest = "Photos of the Restaurant";
const txtAudioRecordings = "Audio Recordings";
const txtRestaurantVideos = "Videos of the Restaurants";
const txtYoutubeVideoRest = "On Youtube Videos at Restaurant";
const txtSelectPhotos = "Select Photos";
const txtSelectVideos = "Select videos";
const txtSend = "Send";
const txtCancel = "Cancel";
const txtListOfRestaurant = "List Of Restaurants";
const txtAddRestaurant = "Add Restaurant";
const txtAddFoodMenu = "Add Food Menu";
const txtRestaurantName = "Name of Restaurant";
const txtPrice = "Price : ";
const txtCreatedDate = "Created : ";
const txtModifiedDate = "Modified : ";
const txtView = "View";
const txtEdit = "Edit";
const txtLookAtRestaurant = "Look At The Restaurant";
const txtLookAtMenu = "Look At The Menu";
const txtDetailsOfRestaurant = "Details of the Restaurant";
const txtMenuDetails = "MENU DETAILS";
const txtMinimumAllowPeople = "Minimum allowed people";
const txtMaximumAllowPeople = "Maximum allowed people";
const txtCreated = "Created";
const txtWidth = "Width";
const txtLength = "Length";
const txtState = "State";
const txtSelectCategory = "Select categories";
const txtSelectService = "Select services";
const txtFeactures = "Feactures";
const txtMediaSelection = "Media Selection";
const txtYoutubeVideoLink = "On Youtube Video At Restaurants";
const txtVideoLink = "Video Link";
const txtOtherRestaurantDetail = "Other Restaurant Detail";
const txtRestaurantAddress = "Address Of Restaurant";
const txtAddMenu = "Add Menu";
const txtRestMenu = "Restaurant Menus";
const txtMenuName = "Menu name";
const txtMenuPrice = "Price";
const txtMenuComposition = "MENU COMPOSITION";
const txtManageMenu = "MANAGE MENUS";
const txtAddFoodMenuC = "ADD THE FOOD MENU";
const txtSelectPhoto = "Select Photo";
const txtBiographyOfSinger = "Biography of the singer";
const txtAddress = "Address";
const txtSelectAudios = "Select Audios";

const txtContent = "CONTENT";
const txtBusinessHistory = "Business History";
const txtAddress = "Address";
const txtHistory = "History";
const txtPrice = "Price €";
const txtNote = "Note:In the case of price you have two options:\n1.If you want your price to appear on your MyDasma profile, then enter it (eg if your price is 2000 euros, enter 2000).\n2. If you do not want your price to appear on your MyDasma profile, then do not post it, leave the space blank.";
const txtHintPrice = "Enter Price(Euros)";

// Validations msg
const errEmptyEmail = "Email is empty";
const errNotValidEmail = "Email is not valid";
const errEmptyPassword = "Password is empty";
const errSelectUserType = "Please select user type";
const errEmptyBusinessName = "Business name is empty";
const errTypeBusinessEmpty = "Type of business is empty";
const errEmptyName = "Name is empty";
const errEmptySurname = "Surname is empty";
const errEmptyPhoneNumber = "Phone number is empty";
const errEmptyConfirmPass = "Confirm password is empty";
const errNotMatchConfirmPass = "Confirm password dose not match with password";
const errSelectCountry = "Please select your country";
const errSelectCity = "Please select your city";
const errEmptyHouseNo = "Number of house is empty";
const errEmptyStreet = "Street is empty";
const errEmptyNeighbourhood = "Neighborhood is empty";
const errEmptyPostCode = "Post code is empty";
const errSelectYourBirthdate = "please select your birthdate";
const errPasswordNotValid = "Password is not valid";
const errNoFileChoose = "No File chosen";
const errEmptyHistory = "History is empty";
const errEmptyAddress = "Address is empty";


// Fix category
const catRest = "RESTAURANTS";
const catSinger = "SINGERS";
const catCameraman = "CAMERAMAN";
const catPhotographer = "PHOTOGRAPHER";
const catCameraPhotographer = "CAMERAMAN AND PHOTOGRAPHER";
const catDecoration = "DECORATION";
const catMakeup = "HAIRDRESSERS AND MAKE-UP";
const catDJ = "DJ";
const catDancer = "DANCER";

// Static content (remove after api call)

const resDescription = "Eclipse Resort is one of the largest resorts in Albania and the region. With many years of experience and well-qualified staff, Eclipse Resort offers high quality service and warmth to all potential guests. The space and staff of the hotel provide you with unprecedented comfort and convenience elsewhere. Any party (merry / wedding,…) can only make sense at the Eclipse Complex. The resort also features summer and winter swimming pools. And, above all, Eclipse Resort is the most beautiful and amazing place possible for your wedding, because the complex has 3 brilliant wedding halls, with capacities from 150, 250 and 450 people. Meanwhile, if you have dreamed of organizing a real wedding like in fairy tales, then such a thing you can make a reality quite easily through the online platform MyDasma.";






